### ISSUE TITLE
Comment in Docs Order Incorrect

### ISSUE THREAD

**Issue by deadcoder0904** [microlinkhq/metascraper#145]
Go to [Write your own rules](https://metascraper.js.org/#/?id=write-your-own-rules) & check out the comment section

```js
// They receive as parameter:
// - `htmlDom`: the cheerio HTML instance.
// - `url`: The input URL used for extact the content.
// - `meta`: The current state of the information detected.
({ htmlDom: $, meta, url: baseUrl }) => wrap($ => $('meta[property="og:logo"]').attr('content'))
```

The order in comments is `htmlDom`, `url`, & `meta`.

While function has order `({ htmlDom: $, meta, url: baseUrl })`.

Which one is correct?

**Comment by Kikobeats** [comment]
Fixed! Thanks

**Comment by deadcoder0904** [comment]
> The order doesn't matter because it's an object path

Ahaha, forgot about destructuring lol 😂

**Comment by deadcoder0904** [comment]
Still not fixed tho :)

![MetaScraper](https://imgur.com/ljWt3RC.png)

**Comment by Kikobeats** [comment]
I'm seeing it correct 🤔 

Can you edit the file and make a PR?
